apiVersion: apps/v1
kind: Deployment
metadata:
  name: canopy-api

spec:
  replicas: 3

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: canopy-api

  template:
    metadata:
      labels:
        app: canopy-api

    spec:
      initContainers:
        - name: create-data-folders
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /data/CanopyResults /data/jsonLinks /data/logging
          volumeMounts:
            - name: canopy-storage
              mountPath: /data

      containers:
        - name: canopy-api
          image: canopy-api:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 80

          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: canopy-secret
                  key: API_KEY

            - name: APP_DATA_PATH
              value: /data

          volumeMounts:
            - name: canopy-storage
              mountPath: /data

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: canopy-storage
          persistentVolumeClaim:
            claimName: canopy-data-pvc
